yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/',
         views.post_edit,
         name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='Posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Группа',
        help_text='Название группы'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Уникальный ID',
        help_text='ID группы'
    )
    description = models.TextField(
        verbose_name='Описание группы',
        help_text='Подробнее'
    )

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Текст нового поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Автор поста'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа поста'
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django import forms

from posts.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from posts.forms import PostForm
from posts.models import Group, Post, User
from yatube.settings import PAGE


def get_one_page(request, posts):
    paginator = Paginator(posts, PAGE)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    return render(
        request,
        'posts/index.html',
        {'page_obj': get_one_page(request, Post.objects.all())}
    )


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = get_one_page(request, posts)
    return render(
        request,
        'posts/group_list.html',
        {'page_obj': page_obj, 'group': group}
    )


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = get_one_page(request, posts)
    return render(
        request,
        'posts/profile.html',
        {'page_obj': page_obj, 'author': author}
    )


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'posts/post_detail.html', {'post': post})


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{% if form.instance.id %}Редактируем пост{% else %}Добавляем пост{% endif %}{% endblock %}
{% block content %}
  {% load user_filters %}
  {% if form.errors %}
    {% for field in form %}
      {% for error in field.errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endif %}
  <form method="post" {% if post  %} action="{% url 'posts:post_edit' post_id=post.id %}" {% endif %}>
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group row my-3"
        {% if field.field.required %}
          aria-required="true"
        {% else %}
          aria-required="false"
        {% endif %}>
        <label for="{{ field.id_for_label }}">
          {{ field.label }}
          <span class="required text-danger">*</span>
        </label>
        <div>
          {{ field|addclass:'form-control' }}
          {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
              {{ field.help_text|safe }}
            </small>
          {% endif %}
        </div>
      </div>
    {% endfor %}
    <div class="d-flex justify-content-end">
      <button type="submit" class="btn btn-primary">
        {% if form.instance.id %}Изменить запись{% else %}Добавить запись{% endif %}
      </button>
    </div>
  </form>
{% endblock%}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Посты выбранной группы{% endblock %}
{% block content %}
<h1>{{ group.title }}</h1>
  <p>
    {{ group.description|linebreaks }}
  </p>
{% for post in group.posts.all %}
  <article>
    <ul>
      <li>
        Автор:
        <a href="{% url 'posts:profile' post.author.username %}">{{ post.author.username }}</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>
      {{ post.text|linebreaks }}
    </p>
  </article>
{% endfor %}
{% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Главная страница{% endblock %}
{% block content %}

{% for post in page_obj %}

<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
</ul>
<p>{{ post.text }}</p>
{% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
{% endif %}
{% if not forloop.last %}
<hr>{% endif %}
{% endfor %}

{% include 'includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}Пост подробно {{post.text|truncatechars:30}}{% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации:
        {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}
      <li class="list-group-item">
        Все записи группы
        <a href="{% url 'posts:group_list' post.group.slug %}">
          {{post.group.title}}</a>
      </li>
      {% endif %}
      <li class="list-group-item">
        Автор:
        <a href="{% url 'posts:profile' post.author.username %}"> {{post.author.username}}</a>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: <span>
        {{post.author.posts.count}}</span>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p class="test">
      {{ post.text|linebreaks }}
    </p>
  </article>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Страница профиля {{author.username}}{% endblock %}
{% block content %}
  <h3>Всего постов: {{author.posts.count}}</h3>
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          <a href="{% url 'posts:profile' post.author.username %}">Все посты автора</a>: {{post.author.username}}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>
        <p class="test"> {{ post.text|linebreaks }}</p>
      </p>
      <a href="{% url 'posts:post_detail' post.pk%}">подробная информация </a>
    </article>
    {% if post.group %}
    Все записи группы
      <a href="{% url 'posts:group_list' post.group.slug %}">{{post.group.title}}</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
{% endblock %}